EXCEPTION: caError: you did something wrong: arbitrary remote error
    at new caError (/home/dap/ca-work/lib/ca/ca-error.js:65:9)
    at stack2 (/home/dap/ca-work/tst/library/tst.error_stacktrace.js:15:10)
    at stack1 (/home/dap/ca-work/tst/library/tst.error_stacktrace.js:9:10)
    at Timer.callback (/home/dap/ca-work/tst/library/tst.error_stacktrace.js:37:8)
Caused by: EXCEPTION: caError: arbitrary remote error
    at new caError (/home/dap/ca-work/lib/ca/ca-error.js:65:9)
    at stack3 (/home/dap/ca-work/tst/library/tst.error_stacktrace.js:20:10)
    at stack2 (/home/dap/ca-work/tst/library/tst.error_stacktrace.js:14:14)
    at stack1 (/home/dap/ca-work/tst/library/tst.error_stacktrace.js:9:10)
    at Timer.callback (/home/dap/ca-work/tst/library/tst.error_stacktrace.js:37:8)
EXCEPTION: Error: Error: generic V8 error
    at stack4 (/home/dap/ca-work/tst/library/tst.error_stacktrace.js:25:10)
    at stack1 (/home/dap/ca-work/tst/library/tst.error_stacktrace.js:9:10)
    at Timer.callback (/home/dap/ca-work/tst/library/tst.error_stacktrace.js:40:8)
